spring.application.name=lms

spring.datasource.url=jdbc:postgresql://localhost:5433/lmsdatabase
spring.datasource.username=postgres
spring.datasource.password=92188162
spring.datasource.class-driver-name=org.postgresql.Driver
spring..jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE


